# Generated by Django 2.0.7 on 2019-09-03 19:57

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Event',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('create_date', models.DateField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='EventDate',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('start', models.DateField()),
                ('end', models.DateField()),
                ('event', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='dates', to='events.Event')),
            ],
        ),
        migrations.CreateModel(
            name='EventLocation',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('address', models.TextField()),
                ('date', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='location', to='events.EventDate')),
                ('event', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='location', to='events.Event')),
            ],
        ),
        migrations.CreateModel(
            name='EventPoster',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='')),
                ('event', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='posters', to='events.Event')),
            ],
        ),
        migrations.CreateModel(
            name='EventPosterDescription',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('description', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='EventTitle',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=250)),
                ('event', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='title', to='events.Event')),
            ],
        ),
        migrations.CreateModel(
            name='Language',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=250)),
            ],
        ),
        migrations.AddField(
            model_name='eventtitle',
            name='language',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='events.Language'),
        ),
        migrations.AddField(
            model_name='eventposterdescription',
            name='language',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='events.Language'),
        ),
        migrations.AddField(
            model_name='eventposterdescription',
            name='poster',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='description', to='events.Event'),
        ),
        migrations.AddField(
            model_name='eventlocation',
            name='language',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='events.Language'),
        ),
    ]
